version: 2
jobs:
  BuildAndTest:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make dev
      - run:
          name: Run Tests
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox && tox
      - store_artifacts:
          path: htmlcov/
      - save_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
          paths:
            - "venv"
            - ".tox"
  Deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make dev
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $pypi-api-token" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            make package
      - save_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
          paths:
            - "venv"
            - ".tox"
      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/*
workflows:
  version: 2
  CorpTools:
    jobs:
      - BuildAndTest
      - Deploy:
          requires:
            - BuildAndTest
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/